# Generated by Django 4.2.6 on 2023-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('engine', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('type_of', models.CharField(max_length=100)),
            ],
        ),
    ]
